### ISSUE TITLE
Removed from chrome web store?

### ISSUE THREAD

**Issue by qqgg231** [louisbarclay/nudge#106]
Extension page gives 404.

@louisbarclay could you reupload?

**Comment by albertopasqualetto** [comment]
Edge says it can be potentially dangerous

**Comment by qqgg231** [comment]
> Edge says it can be potentially dangerous

Probably false positive, as code is open source.

For the time being I am using this extension by side-loading as described [here](https://github.com/louisbarclay/nudge/blob/master/instructions.md):

> To run your local version of Nudge in your browser, use Chrome's developer tool 'Load unpacked extension' and select the extension folder.

**Comment by louisbarclay** [comment]
Hi both - sorry for delayed response.

Nudge was pulled from Chrome Web Store because YouTube Autoplay Stopper feature was broken, meaning I violated the Inaccurate Description policy. I fixed it and reuploaded, but they still said it was broken. Possible that they were on a YouTube version which the feature didn't work on. Very weird that it was pulled from the Web Store because of a broken feature - that's never happened to me before, and there must be tens of thousands of extensions with broken features out there. See screenshots below.

My laptop was stolen a week ago along with my dev set up, and I'm completely slammed with other projects at the moment, so I don't have an ETA for getting this live again.

![image](https://user-images.githubusercontent.com/21208811/120338337-6eb38680-c2f4-11eb-9f3e-7cc849187cfa.png)

![image](https://user-images.githubusercontent.com/21208811/120338392-7c690c00-c2f4-11eb-891d-226b4b4bca0f.png)

**Comment by qqgg231** [comment]
@louisbarclay It really sucks it was stolen. This can wait, take care of things which are most important to you first 🙂.

**Comment by louisbarclay** [comment]
I managed to get my laptop back! Long story. Data was wiped though.

Anyway - I've just fixed the Autoplay Stopper more robustly, hopefully, and re-submitted to Chrome Web Store. Quite nervous about them accepting it - feels like they are not liking Nudge much these days. To appease them, I added a disclaimer that the Autoplay Stopper may not always work. Let's see what happens.

**Comment by arvkr** [comment]
Hoping it gets accepted, super useful extension especially in YouTube!

**Comment by louisbarclay** [comment]
Nudge is live again, woohoo! Closing this now.
