### ISSUE TITLE
Twitter: how to hide things on right side

### ISSUE THREAD

**Issue by karolzlot** [louisbarclay/nudge#116]
I think extension isn't working for me in case of Twitter. It works on youtube/ facebook.

<img src="https://user-images.githubusercontent.com/11590960/128766617-3caece1e-8fea-42ad-823c-85bc15c384da.png"  width="350" />

<img src="https://user-images.githubusercontent.com/11590960/128766572-dcf166e4-6588-40e3-9118-021a65116d92.png"  width="400" />

**Comment by karolzlot** [comment]
After switching to English it is the same.

**Comment by karolzlot** [comment]
I tried to fix it myself, but I coudn't find in which file I should start looking.

**Comment by th0rgall** [comment]
Hey, I'm sorely missing Nudge's Hider on Twitter as well, so did a bit of digging. For me it's the Feed itself that isn't working.

> I tried to fix it myself, but I coudn't find in which file I should start looking.

@karolzlot the file you want is `hidees.js`: https://github.com/louisbarclay/nudge/blob/master/extension/js/vars/hidees.js. 

However, that file is generated from a Google Sheet (an old version is included in github)


There are several issues 

It `hidees.js`

@karolzlot

**Comment by th0rgall** [comment]
I fixed the Google Sheets API syncing here https://github.com/louisbarclay/nudge/pull/122.

It actually seems that the latest hidees in Louis' hidees sheet are actually already fixing the issue with Twitter (see screenshot):

<img width="1047" alt="Screenshot 2021-10-03 at 18 30 14" src="https://user-images.githubusercontent.com/11543641/135761365-cab7046b-6e0a-4cb9-8f5e-b759fdb77bc3.png">

The underlying issue was then the Google API deprecation fixed above. I assume this was what happened:
1. The last time the [hidees.js in this repo](https://github.com/louisbarclay/nudge/blob/master/extension/js/vars/hidees.js) were updated was on January 22, 2021. The version of nudge in this repo is `1.0.0`, and the version in the Chrome store is `1.0.74` which was last updated on June 22, 2021.
2. Twitter broke. Louis fixed it, but didn't deploy a new extension version to the Chrome store. The fix got pulled by clients via the syncing functionality. 
2. Google [turned down the v3 API on August 2, 2021](https://cloud.google.com/blog/products/g-suite/migrate-your-apps-use-latest-sheets-api).
3. Twitter hiding didn't work anymore, since the app probably fell back on the June 22 hidees.js. @karolzlot reported this.

**Comment by louisbarclay** [comment]
Thanks a lot for this @th0rgall! I've now released a new version of Nudge to the Chrome Web Store including your latest fixes to the Twitter hidees. I've also made you an admin of the Google Sheet. @karolzlot if you'd also like to be an admin, to be able to add new hidees, let me know.

**Comment by karolzlot** [comment]
@louisbarclay Yes, you can add me. If you add me I may use it in future if something will need to be improved.

**Comment by louisbarclay** [comment]
Great. Send a Google Sheets-compatible email to hi@louis.work.
